/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2022-06-09 04:06:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.hjb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/EGIS/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850416000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <SCRIPT language=\"JavaScript\" type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://map.vworld.kr/js/vworldMapInit.js.do?apiKey=10036FCE-3940-374C-B2ED-E6FBDF47CFA9\"></SCRIPT>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://map.vworld.kr/js/vworldMapInit.js.do?apiKey=10036FCE-3940-374C-B2ED-E6FBDF47CFA9\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/ol3/3.11.1/ol.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cont1 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map_mode {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 90%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tz-index: 99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mainMenu {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item {\r\n");
      out.write("\tborder-top: 1px solid #ef584a;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 15px 20px;\r\n");
      out.write("\tbackground-color: #ff6f61;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:before {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 0;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tborder-left: 8px solid transparent;\r\n");
      out.write("\tborder-right: 8px solid transparent;\r\n");
      out.write("\tborder-top: 10px solid #ff6f61;\r\n");
      out.write("\tright: 15px;\r\n");
      out.write("\tbottom: -10px;\r\n");
      out.write("\tz-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn i {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu {\r\n");
      out.write("\tbackground: #273057;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttransition: max-height 0.7s;\r\n");
      out.write("\tmax-height: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 15px 20px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tborder-bottom: 1px solid #394c7f;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:before {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: opacity 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:hover:before {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\twidth: 6px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("\t/* background-color: #d8d824; */\r\n");
      out.write("\tborder-top: 24px solid transparent;\r\n");
      out.write("\tborder-left: 11px solid #fcdc29;\r\n");
      out.write("\tborder-bottom: 24px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:after {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: opacity 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:hover:after {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\twidth: 6px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("\t/* background-color: #d8d824; */\r\n");
      out.write("\tborder-top: 24px solid transparent;\r\n");
      out.write("\tborder-right: 11px solid #fcdc29;\r\n");
      out.write("\tborder-bottom: 24px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:hover {\r\n");
      out.write("\tbackground: #273057;\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #273057 0%, #273057 50%, #394c7f 51%, #394c7f\r\n");
      out.write("\t\t100%);\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #273057 0%, #273057 50%, #394c7f 51%,\r\n");
      out.write("\t\t#394c7f 100%);\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #273057 0%, #273057 50%, #394c7f 51%, #394c7f\r\n");
      out.write("\t\t100%);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#273057',\r\n");
      out.write("\t\tendColorstr='#394c7f', GradientType=0);\r\n");
      out.write("\ttransition: all 0.3s;\r\n");
      out.write("\tborder-bottom: 1px solid #394c7f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subMenu a:last-child {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item:target .subMenu {\r\n");
      out.write("\tmax-height: 10em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>홍정범</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header style=\"text-align: center;\">\r\n");
      out.write("\t\t<a href=\"\"> <img style=\"height: 100%;\"\r\n");
      out.write("\t\t\tsrc=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\talt=\"\" /></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<textarea>장소 검색 하기</textarea>\r\n");
      out.write("\t<button>검색</button>\r\n");
      out.write("\t<div id=\"cont1\"></div>\r\n");
      out.write("\t<!--  <button type=\"button\" onclick=\"javascript:setPanZoomBar();\">네비게이션 컨트롤러 설정</button>-->\r\n");
      out.write("\t<div id=\"map_mode\">\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:vworld.setMode(0);\"\r\n");
      out.write("\t\t\tname=\"mode0\">2D배경지도</button>\r\n");
      out.write("\t\t<!-- setMode(0) 배경 (1) 항공 (2)3D -->\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:vworld.setMode(1);\"\r\n");
      out.write("\t\t\tname=\"mode1\">2D항공사진</button>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- SAMPLE -->\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<ui class=\"mainMenu\">\r\n");
      out.write("\t\t<li class=\"item\" id=\"account\"><a href=\"#account\" class=\"btn\"><i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-user-circle\"></i>마커옵션</a>\r\n");
      out.write("\t\t\t<div class=\"subMenu\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"javascript:addMarkingEvent();\"\r\n");
      out.write("\t\t\t\t\t\tname=\"addpin\">마커찍기</button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"clearMarkers()\">전체 마커 삭제</button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<!-- \t<button type=\"button\" onclick=\"removeMarkingEvent()\">선택마커삭제</button> -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"content\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"10\" cols=\"50\" class=\"mkContent\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"내용을 입력하세요.\"></textarea>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"item\" id=\"about\"><a href=\"#about\" class=\"btn\"><i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-address-card\"></i>지도옵션</a>\r\n");
      out.write("\t\t\t<div class=\"subMenu\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:addThemeLayer('지적도','LP_PA_CBND_BUBUN,LP_PA_CBND_BONBUN');\"\r\n");
      out.write("\t\t\t\t\t\tname=\"addcache\">지적도 예시</button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" onclick=\"javascript:importWMS();\"\r\n");
      out.write("\t\t\t\t\tname=\"importwms\">'시도' 주제도</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"javascript:importWMS();\"\r\n");
      out.write("\t\t\t\t\tname=\"importwms\">'시군구' 주제도</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"javascript:importWMS();\"\r\n");
      out.write("\t\t\t\t\tname=\"importwms\">'졸음쉼터 on'</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <p>\r\n");
      out.write("\t\t\t\t\t<select id=\"select_wms\">\r\n");
      out.write("\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ112'>관리지역</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_DGMAINBIZ'>주요상권</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ113'>농림지역</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ111'>도시지역</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<select id=\"delect_wms\">\r\n");
      out.write("\t\t\t\t\t\t<option>삭제</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ112'>관리지역</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_DGMAINBIZ'>주요상권</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ113'>농림지역</option>\r\n");
      out.write("\t\t\t\t\t\t<option value='LT_C_UQ111'>도시지역</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t</ui>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(\"#delect_wms\").change(function() {\r\n");
      out.write("\t\t\t\tvar title = $(\"#delect_wms option:selected\").text(); //선택값의 text값\r\n");
      out.write("\t\t\t\tconsole.log(title);\r\n");
      out.write("\t\t\t\tmap.hideThemeLayer(title); //레이어 숨기기\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#select_wms\").change(function() {\r\n");
      out.write("\t\t\t\t//console.log($(this).val());\r\n");
      out.write("\t\t\t\t//console.log($(\"#select_wms option:selected\").text());\r\n");
      out.write("\t\t\t\tvar title = $(\"#select_wms option:selected\").text();\r\n");
      out.write("\t\t\t\tvar layer = $(this).val(); //선택값의 벨류값.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tmap.showThemeLayer(title, {\r\n");
      out.write("\t\t\t\t\tlayers : layer\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/*map.showThemeLayer(title, {\r\n");
      out.write("\t\t\t\t\tlayers : layer\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction test(title, layer) {\r\n");
      out.write("\t\t\t\tmap.showThemeLayer(title, {\r\n");
      out.write("\t\t\t\t\tlayers : layer\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("            <li class=\"item\" id=\"support\">\r\n");
      out.write("                <a href=\"#support\" class=\"btn\"><i class=\"fas fa-info\"></i>Support</a>\r\n");
      out.write("                <div class=\"subMenu\">\r\n");
      out.write("                    <a href=\"\">item-1</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"item\">\r\n");
      out.write("                <a href=\"#\" class=\"btn\"><i class=\"fas fa-sign-out-alt\"></i>Log Out</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ui>\r\n");
      out.write("         -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p\r\n");
      out.write("\t\t\tstyle=\"color: white; font-color: white; font-size: 20px; text-align: center;\">\r\n");
      out.write("\t\t\t마커 좌표(구글좌표): <input type=\"text\" name='q' id='mousex' value=\"0\"\r\n");
      out.write("\t\t\t\tmaxlength=\"20\"\r\n");
      out.write("\t\t\t\tstyle=\"ime-mode: active; width: 150px; height: 20px; font-size: 20px; background-color: black; color: white;\" />\r\n");
      out.write("\t\t\t<input type=\"text\" name='q' id='mousey' value=\"0\" maxlength=\"20\"\r\n");
      out.write("\t\t\t\tstyle=\"ime-mode: active; width: 150px; height: 20px; font-size: 20px; background-color: black; color: white;\" />\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p style=\"color:white; font-size:20px;\">지도 검색 결과 예시 1</p>\r\n");
      out.write("\t\t<p style=\"color:white; font-size:20px;\">지도 검색 결과 예시 2</p>\r\n");
      out.write("\t\t<p style=\"color:white; font-size:20px;\">지도 검색 결과 예시 3</p>\r\n");
      out.write("\t\t<p style=\"color:white; font-size:20px;\">지도 검색 결과 예시 4</p>\r\n");
      out.write("\t\t<p style=\"color:white; font-size:20px;\">지도 검색 결과 예시 5</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 마커  및 옵션--\r\n");
      out.write("\t\r\n");
      out.write("\t<button id=\"button_maker\">마커 옵션</button>\r\n");
      out.write("\t<div id=\"Maker\" >\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:addMarkingEvent();\"\r\n");
      out.write("\t\t\tname=\"addpin\">마커찍기</button>\r\n");
      out.write("\t\t<p class=\"content\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<textarea rows=\"10\" cols=\"50\" class=\"mkContent\"\r\n");
      out.write("\t\t\t\tplaceholder=\"내용을 입력하세요.\"></textarea>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:testMarker.hide();\"\r\n");
      out.write("\t\t\tname=\"addpin\">마커숨기기1</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:testMarker.show();\"\r\n");
      out.write("\t\t\tname=\"addpin\">마커나타내기</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"clearMarkers()\">전체 마커 삭제</button>\r\n");
      out.write("\t\t마우스클릭(구글좌표): <input type=\"text\" name='q' id='mousex' value=\"0\"\r\n");
      out.write("\t\t\tmaxlength=\"20\" style=\"ime-mode: active\" /> <input type=\"text\"\r\n");
      out.write("\t\t\tname='q' id='mousey' value=\"0\" maxlength=\"20\"\r\n");
      out.write("\t\t\tstyle=\"ime-mode: active\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 지적도 --\r\n");
      out.write("\t<div id=\"Layer\" >\r\n");
      out.write("\t\r\n");
      out.write("\t\t<button type=\"button\"\r\n");
      out.write("\t\t\tonclick=\"javascript:addThemeLayer('지적도','LP_PA_CBND_BUBUN,LP_PA_CBND_BONBUN');\"\r\n");
      out.write("\t\t\tname=\"addcache\">지적도On/Off</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t<!-- button type=\"button\" onclick=\"javascript:addTileCache();\" name=\"addcache\"> 산사태위험지도 On/Off</button> -->\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/**************지도생성 **************/\r\n");
      out.write("\r\n");
      out.write("\t\tvar map = null;\r\n");
      out.write("\t\tvworld.showMode = false;\r\n");
      out.write("\t\tvworld.init(\"cont1\", \"raster-first\", function() { //raster-first => 항공 사진, map-first 배경지도\r\n");
      out.write("\t\t\tmap = this.vmap;\r\n");
      out.write("\t\t\tmap.setBaseLayer(map.vworldBaseMap);\r\n");
      out.write("\t\t\tmap.setControlsType({\r\n");
      out.write("\t\t\t\t\"simpleMap\" : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmap.setCenterAndZoom(14324819.234423, 4277895.4428245, 20); // 맵생성시 바라보는 화면\r\n");
      out.write("\t\t\tmap.addVWORLDControl(\"zoomBar\");\r\n");
      out.write("\t\t\t//map.addVWORLDControl(\"indexMap\");\r\n");
      out.write("\t\t\t//map.setIndexMapPosition(\"right-bottom\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"init\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"zoomin\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"zoomout\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"zoominbox\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"zoomoutbox\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"pan\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"prev\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"next\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"info\");\r\n");
      out.write("\t\t\t//map.addMapToolButton(\"fullext\");\r\n");
      out.write("\t\t\tmap.addMapToolButton(\"caldist\");\r\n");
      out.write("\t\t\tmap.addMapToolButton(\"calarea\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*******마커 옵션 팝업 추가 *******\r\n");
      out.write("\t\t\taddMarker(\r\n");
      out.write("\t\t\t\t\t14324819.234423,\r\n");
      out.write("\t\t\t\t\t4277895.4428245,\r\n");
      out.write("\t\t\t\t\t'이지스<br>'); //맵생성시 마커 생성*/\r\n");
      out.write("\t\t}, function(obj) {\r\n");
      out.write("\t\t\tSOPPlugin = obj;\r\n");
      out.write("\t\t}, function(msg) {\r\n");
      out.write("\t\t\talert('oh my god');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction setModeCallback() {\r\n");
      out.write("\t\t\tvworld.setModeCallback(modecallback);\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction setPanZoomBar() {\r\n");
      out.write("\t\t\tvar pZoomBar = null;\r\n");
      out.write("\t\t\tif (map.getControlsByClass(\"vworld.PanZoomBar\")[0] != null) {\r\n");
      out.write("\t\t\t\tpZoomBar = map.getControlsByClass(\"vworld.PanZoomBar\")[0];\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpZoomBar = new vworld.PanZoomBar();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tpZoomBar.initialize({\r\n");
      out.write("\t\t\t\tzoomStopWidth : 100,\r\n");
      out.write("\t\t\t\tzoomStopHeight : 20,\r\n");
      out.write("\t\t\t\tsliderEvents : null,\r\n");
      out.write("\t\t\t\tzoombarDiv : null,\r\n");
      out.write("\t\t\t\tmeasureDiv : null,\r\n");
      out.write("\t\t\t\tmeasurebuttons : null,\r\n");
      out.write("\t\t\t\tdivEvents : null,\r\n");
      out.write("\t\t\t\tisSimpleBar : false,\r\n");
      out.write("\t\t\t\tcurPosition : 'right',\r\n");
      out.write("\t\t\t\tzoomWorldIcon : null,\r\n");
      out.write("\t\t\t\tforceFixedZoomLevel : false,\r\n");
      out.write("\t\t\t\tmouseDragStart : null,\r\n");
      out.write("\t\t\t\tdeltaY : null,\r\n");
      out.write("\t\t\t\tzoomStart : null\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tpZoomBar.redraw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/** 버튼 **\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on('click', '#button_maker', function() {\r\n");
      out.write("\t\t\talert('마커 옵션');\r\n");
      out.write("\t\t\t$(\"#Maker\").show();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on('click', '#button_layer', function() {\r\n");
      out.write("\t\t\talert('지도 옵션');\r\n");
      out.write("\t\t\t$(\"#Layer\").show();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/*******마커*******/\r\n");
      out.write("\t\tvar markerControl;\r\n");
      out.write("\t\tfunction addMarkingEvent() {\r\n");
      out.write("\t\t\t$('p.content').show();\r\n");
      out.write("\t\t\tvar pointOptions = {\r\n");
      out.write("\t\t\t\tpersist : true\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (markerControl == null) {\r\n");
      out.write("\t\t\t\tmarkerControl = new OpenLayers.Control.Measure(\r\n");
      out.write("\t\t\t\t\t\tOpenLayers.Handler.Point, {\r\n");
      out.write("\t\t\t\t\t\t\thandlerOptions : pointOptions\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\tmarkerControl.events.on({\r\n");
      out.write("\t\t\t\t\t\"measure\" : mapclick\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.addControl(markerControl);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmap.init();\r\n");
      out.write("\t\t\tmarkerControl.activate();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction removeMarkingEvent() {\r\n");
      out.write("\t\t\tmap.events.unregister('click', this, mapclick);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction mapclick(event) {\r\n");
      out.write("\t\t\tmap.init();\r\n");
      out.write("\t\t\tvar temp = event.geometry;\r\n");
      out.write("\t\t\tvar pos = new OpenLayers.LonLat(temp.x, temp.y);\r\n");
      out.write("\t\t\tvar content = $('p.content').find('textarea.mkContent').val(); /*마커 내용입력*/\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById('mousex').value = pos.lon; /* x축 */\r\n");
      out.write("\t\t\tdocument.getElementById('mousey').value = pos.lat; /* y축 */\r\n");
      out.write("\r\n");
      out.write("\t\t\taddMarker(pos.lon, pos.lat, content, null);/* 마커 생성 x , y ,마커 내용, ?*/\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (content == '') { //메모 내용 없을시\r\n");
      out.write("\t\t\t\talert('마커생성완료');\r\n");
      out.write("\t\t\t} else if (content != null) { //메모 내용 있을시\r\n");
      out.write("\t\t\t\talert('내용입력완료 : ' + content);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction addMarker(lon, lat, message, imgurl) { //마커 생성\r\n");
      out.write("\t\t\tvar marker = new vworld.Marker(\r\n");
      out.write("\t\t\t\t\tlon,\r\n");
      out.write("\t\t\t\t\tlat,\r\n");
      out.write("\t\t\t\t\tmessage,\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t'<img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/>' //팝업속 이미지\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t); \r\n");
      out.write("\t\t\tif (typeof imgurl == 'string') {\r\n");
      out.write("\t\t\t\tmarker.setIconImage('<img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/>'); //마커속 내용이미지\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmarker.setZindex(3);\r\n");
      out.write("\t\t\tmap.addMarker(marker);\r\n");
      out.write("\t\t\ttestMarker = marker;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction clearMarkers() {\r\n");
      out.write("\t\t\tmap.clearMarkers();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/********지적도****/\r\n");
      out.write("\r\n");
      out.write("\t\tfunction addThemeLayer(title, layer) {\r\n");
      out.write("\t\t\tmap.showThemeLayer(title, {\r\n");
      out.write("\t\t\t\tlayers : layer\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction addTileCache() {\r\n");
      out.write("\t\t\tmap.showTileCacheLayer('산사태위험지도', 'SANSATAI', {\r\n");
      out.write("\t\t\t\tmin : 9,\r\n");
      out.write("\t\t\t\tmax : 15\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction setTestProxy() {\r\n");
      out.write("\t\t\talert(OpenLayers.ProxyHost);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction importWMS() {\r\n");
      out.write("\t\t\thMap = map.ImportWMSLayer('li', {\r\n");
      out.write("\t\t\t\turl : 'http://localhost:8090/geoserver/cite/wms',\r\n");
      out.write("\t\t\t\tlayers : 'cite:li',\r\n");
      out.write("\t\t\t\tversion : '1.1.0',\r\n");
      out.write("\t\t\t\tstyle : '',\r\n");
      out.write("\t\t\t\tcrs : 'EPSG:900913',\r\n");
      out.write("\t\t\t\tsrs : 'ESPG:3857',\r\n");
      out.write("\t\t\t\tformat : 'image/png'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\talert('test');\r\n");
      out.write("\t\t\tmap.addLayer(hMap);\r\n");
      out.write("\t\t\tconsole.log(hMap);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/hjb/testmain.jsp(178,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/images/egovframework/example/egislogo.PNG");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/egovframework/example/hjb/testmain.jsp(485,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/images/egovframework/example/egislogo.PNG");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/jsp/egovframework/example/hjb/testmain.jsp(488,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/images/egovframework/example/egislogo.PNG");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
